---

volumes:
  bundle:
  db:

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db:/root/db
    stdin_open: true
    tty: true

  redis:
    image: redis
    ports:
      - 6379:6379
    # volumes:
    #   - 'redis:/data'
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    tmpfs: /app/tmp
    env_file:
      - ".envrc"
    tty: true
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
      - 'app'
    environment:
      - REDIS_URL=redis://redis:6379/0
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/app'